# Generated by Django 4.1.7 on 2023-04-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
